steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'  
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-backend-image', '.']


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-backend-image']
