version: '3.8'

services:
  postgres_db:
    image: postgres:15.14-alpine
    container_name: postgres_db-1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./uploaded_images:/app/uploaded_images
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  mindmap_api:
    build: ./back
    container_name: mindmap_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres_db:5432/${DB_NAME}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCP_REGION: ${GCP_REGION}
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-key.json  # 주석 해제
    volumes:
      - ./back:/app/back  # 소스 코드만 마운트
      - ./gcp-key.json:/app/gcp-key.json:ro  # GCP 인증 키
    ports:
      - "8000:8000"
    command: uvicorn back.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data:
